### ISSUE TITLE
Specify node version

### ISSUE THREAD

**Issue by thinktainer** [pebblecode/node-starter-kit#2]
Would it make sense to lock down to a particular version of node, that is known to work with the npm packages we use? Is it enough to specify in `package.json`? [ndenv](https://github.com/riywo/ndenv) supports an rc file that it evaluates when cd'ing to the directory, maybe that would be a nice addition?

**Comment by tanepiper** [comment]
@thinktainer It's already in https://github.com/pebblecode/node-starter-kit/blob/master/.nvmrc

**Comment by poshaughnessy** [comment]
We have v4 specified in .nvmrc

I think we should also add it to 'engines' in package.json

**Comment by export-mike** [comment]
PR: 
https://github.com/pebblecode/node-starter-kit/pull/3
